django-app/portfolio/main_port/urls.py
from django.urls import path
from .views import main_port_index, about_me_index, contact_index
app_name = 'main_port'
urlpatterns = [
    path('', main_port_index, name='home'),
    path('about_me/', about_me_index, name='about'),
    path('contact/', contact_index, name='contact'),
]

django-app/portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView  # Импорт RedirectView
from django.templatetags.static import static as static_url  # Импорт для статического URL

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main_port/', include('main_port.urls')),
    path('favicon.ico', RedirectView.as_view(url=static_url('favicon.ico'))),
]

# Если нужно добавить главную страницу
urlpatterns += [path('', include('main_port.urls'))]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django-app/portfolio/main_port/models.py
from django.db import models

# Create your models here.

django-app/portfolio/main_port/forms.py
from django import forms



class UserBioForm(forms.Form):
    name = forms.CharField(label="Компания")
    email = forms.CharField(label="Email (для обратной связи)")
    topic = forms.CharField(label="Тема")
    text = forms.CharField(label="Сообщение", widget=forms.Textarea)

django-app/portfolio/main_port/views.py
from django.contrib.sites import requests
from django.http import HttpRequest
from django.shortcuts import render, redirect
from .forms import UserBioForm
from .utils import send_telegram_message
def main_port_index(request: HttpRequest):
    return render(request, 'main_port/main_list_1.html')  # Убедитесь, что шаблон существует


def about_me_index(request):
    return render(request, 'main_port/about_me.html')


# def contact_index(request):
#     context = {
#         "form": UserBioForm(),
#     }
#     return render(request, 'main_port/data_prof.html', context=context)





def contact_index(request):
    if request.method == 'POST':
        form = UserBioForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            topic = form.cleaned_data['topic']
            text = form.cleaned_data['text']

            # Формируем сообщение для отправки
            message = f"Новое сообщение от {name} ({email})\nТема: {topic}\nСообщение: {text}"

            # Отправляем сообщение в Telegram
            chat_id = "877631642"  # Замените на ваш chat_id
            send_telegram_message(chat_id, message)
            return render(request, 'main_port/trash.html')
    else:
        form = UserBioForm()

    return render(request, 'main_port/data_prof.html', {'form': form})

django-app/portfolio/main_port/templates/main_port/about_me.html
{% extends 'main_port/base.html' %}

{% block title %}
Обо мне

{% endblock %}


{% load static %}
{% block body %}
<div class="fixed-container">
    <div>
        <h2>Обо мне</h2>
        <p>Меня зовут Дейс Данил, я Python разработчик.</p>
        <img src="{% static 'img/photo.jpg' %}" alt="Мое фото" style="width: 480px; height: auto;">
    </div>
    <section class="plus_container">
    <div class="scills">

        <p>PYTHON</p>
        <div class="scill-bar">
            <div class="scill-percentage" style="width:50%;"></div>
        </div>

        <p>HTML</p>
        <div class="scill-bar">
            <div class="scill-percentage" style="width:80%;"></div>
        </div>

        <p>DOCKER</p>
        <div class="scill-bar">
            <div class="scill-percentage" style="width:70%;"></div>
        </div>

        <p>CSS</p>
        <div class="scill-bar">
            <div class="scill-percentage" style="width:100%;"></div>
        </div>

        <p>GIT</p>
        <div class="scill-bar">
            <div class="scill-percentage" style="width:36%;"></div>
        </div>

        <p>FLASK</p>
        <div class="scill-bar">
            <div class="scill-percentage" style="width:55%;"></div>
        </div>

        <p>SQL</p>
        <div class="scill-bar">
            <div class="scill-percentage" style="width:70%;"></div>
        </div>


    </div>
</section>

</div>

<section>
    <div class="fixed-container">
        <div class="i_and_me">
            Я начинающий backend разработчик. В данной сфере развиваюсь на протяжении 1 года.
        </div>
    </div>
     <div class="fixed-container">
        <h3>
            Опыт работы
        </h3>
     </div>
    <div class="fixed-container">
        <p>
            <b>Специалист технической поддержки ООО "Яндекс", 2024 - настоящее время</b>
        </p>
    </div>
    <div class="fixed-container">
        <ul class="custom-list">
            <li>Ответы на вопросы пользователей</li>
            <li>Техническая поддержка продуктов</li>
            <li>Обучение новых сотрудников</li>
            <li>Участие в проектах по улучшению сервиса</li>
        </ul>
    </div>
</section>
<section>
    <div class="fixed-container">
        <p>
            <b>Преподаватель ФГБОУ ВО "Алтайский государственный медицинский университет", 2018 г. - 2024 г.</b>
        </p>
    </div>
    <div class="fixed-container">
        <ul class="custom-list">
            <li>Разработка учебных планов и программ</li>
            <li>Проведение лекций и практических занятий</li>
            <li>Индивидуальная работа со студентами</li>
            <li>Участие в научных конференциях</li>
            <li>Разработка и внедрение новых технологий отслеживания успеваемости</li>
        </ul>
    </div>
</section>
<section>
    <div class="fixed-container">
        <h3>
            Образование
        </h3>
    </div>


<div class="fixed-container">
    <ul class="custom-list">

        <div>
            <img src="{% static 'img/ped.jpg' %}" alt="Telegram" width="20" height="20" class="black-and-white">
            <span> Алтайский государственный педагогический университет", математический факультет, 2010 г. - 2015 г.</span>
        </div>
        <div>
            <img src="{% static 'img/scill_2.jpg' %}" alt="Telegram" width="20" height="20" class="black-and-white">
            <span> Курсы Scillbox "Python - разработчик", февраль 2024 г. - декабрь 2024 г.</span>
        </div>
        <div>
            <img src="{% static 'img/21.jpg' %}" alt="Telegram" width="20" height="20" class="black-and-white">
            <span>АНО "Школа 21", 2024 г. - настоящее время</span>
        </div>
    </ul>
</div>
</section>

<section>
    <div class="fixed-container">
        <h3>Навыки</h3>
    </div>

    <div class="fixed-container">
        <ul class="custom-list">
            <li>Знание основ Python (синтаксис, структуры данных)</li>
            <li>Опыт работы с фреймворками (Django, Flask)</li>
            <li>Разработка RESTful API</li>
            <li>Работа с базами данных (SQL, NoSQL)</li>
            <li>Оптимизация производительности приложений</li>
            <li>Тестирование и отладка кода (unittest, pytest)</li>
            <li>Опыт работы с системами контроля версий (Git)</li>
            <li>Понимание основ DevOps (CI/CD)</li>
        </ul>
    </div>
</section>



<footer>
         <div class="fixed-container" style="display: flex; justify-content: space-between; align-items: center;">
            <span>&copy; 2024 Портфолио Python - разработчика</span>
            <div>
                <a href="https://t.me/+79237222518" target="_blank">
                    <img src="{% static 'img/telega.jpg' %}" alt="Telegram" width="30" height="30">
                </a>
                <a href="mailto:danildeis100@mail.ru" target="_blank">
                    <img src="{% static 'img/email.jpg' %}" alt="Email" width="30" height="30">
                </a>
            </div>
        </div>
</footer>
<style>
    .i_and_me {
        width: 50%; /* Ширина 50% от родительского элемента */
        max-width: 500px; /* Максимальная ширина */
        margin: left; /* Центрирование контейнера и отступ сверху */
        color: black; /* Цвет текста */
        padding: 15px; /* Отступы внутри контейнера */
        border-radius: 8px; /* Закругленные углы */
    }
    .custom-list {
        margin-top: 20px; /* Устанавливаем желаемый отступ сверху */
        list-style-type: disc; /* Тип маркеров */
        padding-left: 20px; /* Отступ слева для маркеров */
        margin: 0; /* Убираем отступы по умолчанию */
    }
    .custom-list li {
        margin: 2px 0; /* Устанавливаем небольшие отступы между пунктами списка */
        line-height: 1.2; /* Уменьшаем высоту строки для более компактного вида */
    }
    .fixed-container h3 {
    margin-bottom: 20px; /* Устанавливаем желаемый отступ снизу */
}
    .black-and-white {
    filter: grayscale(100%); /* Применяет черно-белый фильтр */
}

    .scills {
        width: 500px; /* Ширина контейнера */
        padding: 20px; /* Отступы внутри контейнера */
        background-color: #f0f0f0; /* Цвет фона для контейнера */
        border-radius: 8px; /* Закругленные углы */
        margin: 20px auto; /* Центрирование контейнера */
    }

    .scill-bar {
        height: 12px; /* Высота прогресс-бара */
        background-color: white; /* Цвет фона для прогресс-бара */
        border-radius: 4px; /* Закругленные углы */
        margin-bottom: 15px; /* Отступ между прогресс-барами */
    }
    .scill-percentage {
        height: 100%; /* Высота равна высоте родительского элемента */
        background-color: #555; /* Цвет заполненной части прогресс-бара */
        border-radius: 4px; /* Закругленные углы */
    }
    footer {
            margin-top: 30px; /* Установите желаемое значение отступа */
        }

</style>

{% endblock %}

django-app/portfolio/main_port/templates/main_port/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        Base Title
        {% endblock %}
    </title>
    	{% load static %} 
        <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon"> 
        <link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates&display=swap" rel="stylesheet">
    <style>
          body {
            background-color: #f0f0f0; /* Серый фон */
            font-family: 'Montserrat Alternates', sans-serif; /* Использование загруженного шрифта */
            margin: 0;
            padding: 0;
        }
        header {
            background-color: #f0f0f0; /* Цвет фона заголовка */
            padding: 20px; /* Отступы вокруг заголовка */
        }
        .fixed-container {
            max-width: 1000px;
            margin-right: auto;
            margin-left: auto; /* Центрирует контейнер */
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        a {
            margin-left: 20px; /* Расстояние между ссылками */
            text-decoration: none;
            color: black;
        }
        a:hover {
            color: red; /* Цвет ссылки при наведении */
        }
        h3, h6 {
            margin-bottom: 0; /* Устанавливаем желаемый отступ между заголовками и следующими элементами */
        }

        /* Медиазапросы для адаптивного дизайна */
        @media (max-width: 600px) {
            .fixed-container {
                flex-direction: column; /* Изменяет направление на вертикальное */
                align-items: flex-start; /* Выравнивает элементы по левому краю */
            }
            
            a {
                margin-left: 0; /* Убирает отступы между ссылками */
                margin-bottom: 10px; /* Добавляет отступ снизу между ссылками */
            }
        }

    </style>
</head>
<body>

<header>
    <div class="fixed-container">
        <div>
            <span><h3>Портфолио</h3></span>
        </div>
        <div>
            <a href="{% url 'main_port:home' %}">Главная</a>
            <a href="{% url 'main_port:about' %}">Обо мне</a>
            <a href="{% url 'main_port:contact' %}">Контакты</a>
        </div>
    </div>
</header>

{% block body %}
Base Body
{% endblock %}

</body>
</html>

django-app/portfolio/main_port/templates/main_port/data_prof.html
{% extends 'main_port/base.html' %}
{% block title %}
Контакты

{% endblock %}

{% block body %}
<div class="fixed-container">
        <h3>Сообщение</h3>
</div>
<div class="fixed-container">
    <div class="plus_container">
        <h5>Если есть вопросы и предложения по работе, вы можете связаться со мной либо написать в форме ниже</h5>
    </div>
</div>
<div class="fixed-container">
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>  <!-- Название поля сверху -->
                {{ field }}
                {% if field.errors %}
                    <div class="error">{{ field.errors }}</div>  <!-- Ошибки, если есть -->
                {% endif %}
            </div>
        {% endfor %}
        <button type="submit">Отправить</button>
    </form>
    <div class="minus_container">
        <b>Aдрес:</b>
        <p> г. Барнаул, ул.Новгородская, 18 </p>
         <b>Телефон:</b>
        <p> +7 - 923 - 722 -25 - 18</p>
         <b>Email:</b>
        <p> danildeis100@mail.ru</p>
    </div>
</div>
{% load static %}
<footer>
             <div class="fixed-container" style="display: flex; justify-content: space-between; align-items: center;">
                <span>&copy; 2024 Портфолио Python разработчика</span>
                <div>
                    <a href="https://t.me/+79237222518" target="_blank">
                        <img src="{% static 'img/telega.jpg' %}" alt="Telegram" width="30" height="30">
                    </a>
                    <a href="mailto:danildeis100@mail.ru" target="_blank">
                        <img src="{% static 'img/email.jpg' %}" alt="Email" width="30" height="30">
                    </a>
                </div>
            </div>
</footer>

<style>

.plus_container {
    width: 500px; /* Установите желаемую ширину */
    text-align: left; /* Выравнивание текста по левому краю */
    margin: 10px; /* Убираем отступы по умолчанию */
    padding: 0; /* Добавляем внутренние отступы для удобства чтения */
}

h3, h5 { /* Измените h6 на h5, если используете h5 в HTML */
    margin: 0; /* Убираем все отступы у заголовков */
    text-align: left;
}

.minus_container {
    width: 400px; /* Установите желаемую ширину, например 400px */
    height: 300px;
    text-align: left; /* Выравнивание текста по левому краю */
    margin: 10px right; /* Центрируем контейнер и устанавливаем общий отступ */
    overflow-wrap: break-word; /* Перенос длинных слов на новую строку */
}

p {
    font-size: 12px; /* Установите желаемый размер шрифта */
}

b {
    font-size: 15px; /* Установите желаемый размер шрифта */
}
.form-group {
    display: flex;
    flex-direction: column;
    margin-bottom: 10px;
}

input,  select {
    width: 200px; /* Убираем 100% */
    max-width: 300px; /* Устанавливаем максимальную ширину */
}

label {
    margin-bottom: 5px; /* Отступ между меткой и полем ввода */
    width: auto;
}
textarea {
    width: auto; /* Убираем 100% */
    max-width: 300px; /* Устанавливаем максимальную ширину */
}
footer {
    margin-top: 40px; /* Установите желаемое значение отступа */
}



</style>
{% endblock %}

django-app/portfolio/main_port/templates/main_port/main_list_1.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
{% load static %}
<html>
    <head>
	<link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon"> 
        <title>Портфолио Python разработчика</title>
       <link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates&display=swap" rel="stylesheet">
        <style>
            body {
                background-color: #f0f0f0; /* Серый фон */
            }
            * {
                font-family: 'Montserrat Alternates', sans-serif; /* Использование загруженного шрифта */
            }
            html,body{
                margin: 0;
                padding: 0;
            }
            header {
                margin: 0;
                padding: 0 0;
            }
            header > div{
                display: flex;
                justify-content: space-between;
                align-items: center;
            }

            .fixed-container{
                max-width:1000px;
                height: 100%;
                margin-left: auto;
                margin-right: auto;

            }

            .fixed-container h2 {
                margin-bottom: 0;
            }

            .fixed-container p {
                margin-top: 0;
            }
            .first-block > div{
                display: flex;
                flex-direction:column;
                justify-content: center;
                align-items: flex-start;

            }
           .about_me {
                min-height: 200px; /* Минимальная высота контейнера */
                text-align: center; /* Центрирование текста */
                max-width: 600px; /* Максимальная ширина контейнера */
                width: 40%; /* Уменьшите ширину контейнера до 40% */
                margin: 20px auto; /* Центрирует контейнер по горизонтали и добавляет отступ сверху и снизу */
                padding: 20px; /* Внутренние отступы */

            }
        .about_me h4 {
                margin-bottom: 10px;

            }
        .about_me p {
                line-height: 1.6;

            }

            .container {
                display: flex;
                flex-wrap: wrap;
                justify-content: space-between;
            }

            .item {
                flex: 1 1 calc(30% - 10px); /* Устанавливает ширину элемента */
                margin: 10px; /* Отступы вокруг каждого элемента */
                border-radius: 8px; /* Закругленные углы */
                box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            }

            .item img {
                width: 100%;
                height: auto;
            }

            a{
                color: black;
                text-decoration: none;
            }
            a:hover {
                color: red;
                text-decoration: underline;
            }



           .list ul {
                display: flex;
                justify-content: space-between;
                align-items: center;
                padding: 0; /* Убираем отступы */
                margin: 0; /* Убираем внешние отступы */
                font-size: 10px; /* Задайте желаемый размер шрифта */
            }

            .list li {
                margin-right: 10px; /* Отступ между элементами списка */
            }

	    @media (max-width: 600px) { 
           .about_me {
               width: 90%; /* Увеличивает ширину контейнера до 90% на мобильных устройствах */
           }
           .item {
               flex: 1 1 calc(100% - 20px); /* Устанавливает ширину элемента на 100% с учетом отступов */
               margin: 10px 0; /* Убирает боковые отступы */
           }
           .list ul {
               flex-direction: column; /* Изменяет направление списка на вертикальное */
               align-items: flex-start; /* Выравнивает элементы списка по левому краю */
           }
           .list li {
               margin-right: 0; /* Убирает правый отступ между элементами списка */
               margin-bottom: 10px; /* Добавляет отступ снизу между элементами списка */
           }
       }
        </style>
    </head>
    <body>
        <header>
            <div class="fixed-container">
                <div>
                    <span><h3> Портфолио </h3></span>
                </div>
                <div>
                    <a href="{% url 'main_port:home' %}">Главная</a>
                    <a href="{% url 'main_port:about' %}">Обо мне</a>
                    <a href="{% url 'main_port:contact' %}">Контакты</a>
                </div>
            </div>
        </header>

        <section class="first-block">
            <div class="fixed-container">
                <h2>Дейс Данил</h2>
                <p>Python разработчик</p>
            </div>
        </section>


        </section>
            <div class="block-image">
                <div class="fixed-container">
                    <h4>Стек технологий</h4>
                    <div class="container">
                        <div class="item">
                            <img src="{% static 'img/docker.jpg' %}" alt="My Image">

                        </div>
                        <div class="item">
                            <img src="{% static 'img/git_2.jpg' %}" alt="My Image">
                        </div>
                        <div class="item">
                             <img src="{% static 'img/linux.jpg' %}" alt="My Image">

                        </div>
                        <div class="item">
                           <img src="{% static 'img/flask.jpg' %}" alt="My Image">
                        </div>
                        <div class="item">
                            <img src="{% static 'img/python.jpg' %}" alt="My Image">
                        </div>
                        <div class="item">
                            <img src="{% static 'img/sql.jpg' %}" alt="My Image">
                        </div>


                        <div class="item">
                            <img src="{% static 'img/django.jpg' %}" alt="My Image">
                        </div>
                        <div class="item">
                            <img src="{% static 'img/html.jpg' %}" alt="My Image">
                        </div>
                        <div class="item">
                            <img src="{% static 'img/msql.jpg' %}" alt="My Image">
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="about_me">
             <div class="fixed-container">
                 <h4>Мои навыки </h4>
                 <p>Это основной стек технологий, который я использовал при обучении и
                     работе над Pet проектами. Готов изучать другие технологии
                     для дальнейшего развития и становления себя, как профессионала.</p>
             </div>
        </section>
          <footer>
             <div class="fixed-container" style="display: flex; justify-content: space-between; align-items: center;">
                <span>&copy; 2024 Портфолио Python разработчика</span>
                <div>
                    <a href="https://t.me/+79237222518" target="_blank">
                        <img src="{% static 'img/telega.jpg' %}" alt="Telegram" width="30" height="30">
                    </a>
                    <a href="mailto:danildeis100@mail.ru" target="_blank">
                        <img src="{% static 'img/email.jpg' %}" alt="Email" width="30" height="30">
                    </a>
                </div>
            </div>
        </footer>
        <section class="list">
            <div class="fixed-container">
                <ul>
                    Python Java C# C++ JavaScript Ruby PHP Swift Go Kotlin HTML CSS React Angular Vue.js Django Flask Ruby on Rails SQL
                    MySQL PostgreSQL SQLite NoSQL MongoDB Cassandra Redis Docker Kubernetes Vagrant Git IDE PyCharm Visual Studio
                    Code Eclipse Unit testing pytest JUnit Selenium Agile Scrum Kanban TensorFlow Keras scikit-learn Pandas NumPy
                    React Native Flutter Swift Kotlin AWS Google Cloud Platform Microsoft Azure Jenkins Travis CI GitLab CI MVC MVVM
                    OLE COM Unity Unreal Engine Jira Trello
                </ul>
            </div>
        </section>

    </body>
</body>
</html>

django-app/portfolio/main_port/templates/main_port/trash.html
{% extends 'main_port/base.html' %}
{% block title %}Контакты{% endblock %}

{% load static %}
{% block body %}

<div class="derict">
    <div class="image-container">
        <img src="{% static 'img/sub.jpg' %}" alt="Мое фото" class="centered-image">
    </div>
</div>
   <footer>
             <div class="fixed-container" style="display: flex; justify-content: space-between; align-items: center;">
                <span>&copy; 2024 Портфолио Python разработчика</span>
                <div>
                    <a href="https://t.me/+79237222518" target="_blank">
                        <img src="{% static 'img/telega.jpg' %}" alt="Telegram" width="30" height="30">
                    </a>
                    <a href="mailto:danildeis100@mail.ru" target="_blank">
                        <img src="{% static 'img/email.jpg' %}" alt="Email" width="30" height="30">
                    </a>
                </div>
            </div>
    </footer>
<style>
    .fixed-container {
        position: relative; /* Для фиксированного позиционирования, если нужно */
    }

    .derict {
        display: flex; /* Используем Flexbox для центрирования */
        justify-content: center; /* Центрируем по горизонтали */
        align-items: center; /* Центрируем по вертикали */
        height: 100vh; /* Устанавливаем высоту контейнера */
        color: white;
    }

    .image-container {
        max-width: 100%; /* Ограничиваем максимальную ширину изображения */
        height: auto; /* Сохраняем пропорции изображения */
        display: flex;
    }

    .centered-image {
        max-width: 100%; /* Ограничиваем ширину изображения */
        height: auto; /* Сохраняем пропорции изображения */
    }
   body {
            background-color: white; /* Серый фон */
    }
   header {
        background-color: white; /* Цвет фона заголовка */
        padding: 20px; /* Отступы вокруг заголовка */
    }

</style>
{% endblock %}